name: loop_hr
description: Interloop HR Self Services Application.

publish_to: "none"

version: 1.1.0+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_svg: ^0.22.0
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  datetime_picker_formfield: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it: ^7.1.3
  bloc: ^8.0.2
  http: ^0.13.3
  json_annotation: ^4.4.0
  loader_overlay: ^2.0.2
  hive: ^2.0.4
  path_provider: ^2.0.9
  hive_generator: ^1.1.0
  google_fonts: ^2.1.0
  infinite_scroll_pagination: ^3.1.0
  pinput: 1.2.0
  intl_phone_number_input: ^0.7.0+2
  device_info: ^2.0.2
  firebase_messaging: 11.1.0
  firebase_core: 1.10.0
  shimmer: ^2.0.0
  dropdown_search: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  timeago: ^3.1.0
  readmore: ^2.1.0
  intl_phone_field: ^3.0.1

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^6.1.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/logos/app_logo_android_icon.png"
  image_path_ios: "assets/logos/app_logo_ios_new.png"
  adaptive_icon_foreground: "assets/logos/app_logo_android_icon.png"
  adaptive_icon_background: "#2B3747"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/svg-icons/
    - assets/svg-icons/walk-through/
